version: "3"

services:
    pahan:
        build: .
        volumes:
            - /Users/mostobriv/share/git_stuff/test/pahan/logs:/pahan/logs
            - /Users/mostobriv/share/git_stuff/test/pahan/dumps:/pahan/dumps
            - /Users/mostobriv/share/git_stuff/test/pahan/streams:/pahan/streams
        ulimits:
            nproc: 256
            nofile:
                soft: 4096
                hard: 4096
        ports:
            - 8888:8888

    database:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER:     test
            POSTGRES_PASSWORD: test
            POSTGRES_DB:       test