version: "2"

services:
    pahan:
        build: .
        volumes:
            - ./logs:/pahan/logs
            - ./dumps:/pahan/dumps
            - ./streams:/pahan/streams
        ulimits:
            nproc: 1024
            nofile:
                soft: 4096
                hard: 4096
        mem_limit: 256m
        mem_reservation: 128m
    redis:
        image: "redis:5.0.5"
        volumes:
            - ./redis-data:/data
        ports:
            - "6379:6379"
