version: "3"

services:
    pahan:
        build: .
        volumes:
            - ./logs:/pahan/logs
            - ./dumps:/pahan/dumps
            - ./streams:/pahan/streams
        ulimits:
            nproc: 256
            nofile:
                soft: 4096
                hard: 4096

    database:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER:     test
            POSTGRES_PASSWORD: test
            POSTGRES_DB:       test